Sensor_parameters:
  frequency : 100

  pos_offset : 1.0
  pos_gain : 250.0

  neg_offset : 1.0
  neg_gain : -25.25

  atm_offset : 101.325

  
  Pressure_pos_index : 0
  Pressure_neg_index : 1
  Pressure_macro_index : 2


Reference_parameters:
  frequency : 1000

PWM_parameters:
  frequency : 1000

  pid_pos_index : 18
  pid_neg_index : 19

positive_channel:
  n_channel : 3

negative_channel:
  n_channel : 3

MPC_parameters:
  NP : 5
  n_x : 1
  n_u : 3
  Ts : 0.001
  Q_values : 10
  R_values : 1
  pos_ku_micro : 0.2
  pos_ku_macro : 0.05
  pos_ku_atm : 0.4
  neg_ku_micro : 1
  neg_ku_macro : 0.25
  neg_ku_atm : 2
  macro_min : 801.325
  
channel_volume : # mL (= 1e-6m^3)
  pos1 : 1
  pos2 : 1
  pos3 : 1
  neg1 : 1
  neg2 : 1
  neg3 : 1


PID_parameters:
  n_channel : 3

  pos_kp : 0.1
  pos_ki : 0.03
  pos_kd : 0.0

  neg_ki : 0.2
  neg_kp : 0.06
  neg_kd : 0.0

  pos_ref : 301.325
  neg_ref : 51.325

system_parameters :
  pwm_print : true
  mpc_valve_operate : false
  rl_valve_operate : false
